// This file is auto-generated by `npm run types:generate`
// Do not edit manually — regenerate after schema changes
//
// NOTE: `supabase gen types typescript --project-id axxbcsqgqszvgozgaczt`
// requires an authenticated Supabase CLI session (`npx supabase login`),
// which needs an interactive browser and isn't available in this
// environment. This file was hand-authored to exactly match the schema
// defined in `src/database/migrations/001_create_tables.sql`,
// `003_check_constraints.sql`, `006_achievements.sql` and
// `007_input_constraints.sql`, in the same shape the CLI would produce.
// Re-run `npm run types:generate` (`src/app/types/database.types.ts`)
// from an authenticated machine to replace this file with a
// CLI-generated one — the shape should match.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      pomodoro_sessions: {
        Row: {
          id: string;
          user_id: string;
          started_at: string;
          completed_at: string;
          duration_minutes: number;
          session_type: string;
          task_text: string | null;
          completed: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          started_at: string;
          completed_at: string;
          duration_minutes: number;
          session_type?: string;
          task_text?: string | null;
          completed?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          started_at?: string;
          completed_at?: string;
          duration_minutes?: number;
          session_type?: string;
          task_text?: string | null;
          completed?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: 'pomodoro_sessions_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      tasks: {
        Row: {
          id: string;
          user_id: string;
          text: string;
          completed: boolean;
          position: number;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          user_id: string;
          text: string;
          completed?: boolean;
          position?: number;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          text?: string;
          completed?: boolean;
          position?: number;
          updated_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'tasks_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      user_achievements: {
        Row: {
          id: string;
          user_id: string;
          achievement_id: string;
          unlocked_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          achievement_id: string;
          unlocked_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          achievement_id?: string;
          unlocked_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_achievements_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      user_settings: {
        Row: {
          id: string;
          is_pro: boolean;
          start_in_mini_mode: boolean;
          confirm_on_stop: boolean;
          pip_mode_enabled: boolean;
          horizontal_pip_enabled: boolean;
          language: string;
          enable_desktop_notifications: boolean;
          notification_sound_enabled: boolean;
          theme_mode: string;
          selected_theme_id: string;
          background_sound: string;
          volume: number;
          daily_pomodoro_goal: number;
          has_seen_onboarding: boolean;
        };
        Insert: {
          id: string;
          is_pro?: boolean;
          start_in_mini_mode?: boolean;
          confirm_on_stop?: boolean;
          pip_mode_enabled?: boolean;
          horizontal_pip_enabled?: boolean;
          language?: string;
          enable_desktop_notifications?: boolean;
          notification_sound_enabled?: boolean;
          theme_mode?: string;
          selected_theme_id?: string;
          background_sound?: string;
          volume?: number;
          daily_pomodoro_goal?: number;
          has_seen_onboarding?: boolean;
        };
        Update: {
          id?: string;
          is_pro?: boolean;
          start_in_mini_mode?: boolean;
          confirm_on_stop?: boolean;
          pip_mode_enabled?: boolean;
          horizontal_pip_enabled?: boolean;
          language?: string;
          enable_desktop_notifications?: boolean;
          notification_sound_enabled?: boolean;
          theme_mode?: string;
          selected_theme_id?: string;
          background_sound?: string;
          volume?: number;
          daily_pomodoro_goal?: number;
          has_seen_onboarding?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: 'user_settings_id_fkey';
            columns: ['id'];
            isOneToOne: true;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DefaultSchema = Database['public'];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database;
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        Database[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? (Database[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      Database[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] &
        DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database;
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database;
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;
